{{- $key := randAlphaNum 128 | lower }}
{{- $ca := genCA "controller-mutate-ca" 3650 }}
{{- $altName1 := printf "drycc-controller-mutate.%s" .Release.Namespace }}
{{- $altName2 := printf "drycc-controller-mutate.%s.svc" .Release.Namespace }}
{{- $cert := genSignedCert "drycc-controller-mutate" nil (list $altName1 $altName2) 3650 $ca }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ .Release.Namespace }}-controller-mutate
  annotations:
    component.drycc.cc/version: {{ .Values.imageTag }}
  labels:
    heritage: drycc
webhooks:
- name: mutate.drycc.cc
  sideEffects: None
  admissionReviewVersions: ["v1"]
  clientConfig:
    caBundle: {{ (include "common.secrets.lookup" (dict "secret" "controller-mutate-cert" "key" "ca.crt" "defaultValue" $ca.Cert "context" $)) }}
    service:
      name: drycc-controller-mutate
      namespace: "{{ .Release.Namespace }}"
      path: "{{ printf "/v2/mutate/%s/" ((include "common.secrets.lookup" (dict "secret" "controller-mutate-cert" "key" "key" "defaultValue" $key "context" $)) | b64dec) }}"
  failurePolicy: Fail
  objectSelector:
    matchLabels:
      heritage: drycc
  rules:
  - operations: ["UPDATE"]
    apiGroups: ["batch"]
    apiVersions: ["*"]
    resources: ["jobs/status"]
  - operations: ["UPDATE"]
    apiGroups: ["apps"]
    apiVersions: ["*"]
    resources: ["deployments/scale"]
  - operations: ["UPDATE"]
    apiGroups: ["servicecatalog.k8s.io"]
    apiVersions: ["*"]
    resources: ["serviceinstances/status", "servicebindings/status"]
  timeoutSeconds: 30
---
apiVersion: v1
kind: Secret
metadata:
  name: controller-mutate-cert
  annotations:
    component.drycc.cc/version: {{ .Values.imageTag }}
  labels:
    heritage: drycc
type: Opaque
data:
  key: {{ (include "common.secrets.lookup" (dict "secret" "controller-mutate-cert" "key" "key" "defaultValue" $key "context" $)) }}
  ca.key: {{ (include "common.secrets.lookup" (dict "secret" "controller-mutate-cert" "key" "ca.key" "defaultValue" $ca.Key "context" $)) }}
  ca.crt: {{ (include "common.secrets.lookup" (dict "secret" "controller-mutate-cert" "key" "ca.crt" "defaultValue" $ca.Cert "context" $)) }}
  tls.key: {{ (include "common.secrets.lookup" (dict "secret" "controller-mutate-cert" "key" "tls.key" "defaultValue" $cert.Key "context" $)) }}
  tls.crt: {{ (include "common.secrets.lookup" (dict "secret" "controller-mutate-cert" "key" "tls.crt" "defaultValue" $cert.Cert "context" $)) }}
