sudo: required
language: go
services:
  - docker
script: 
  - DEV_REGISTRY="docker.io" make test
  - DEV_REGISTRY="docker.io" make docker-build-test upload-coverage
notifications:
  slack:
    rooms:
      - drycc:xKmLlmJR4hfRAgVIOwdpAoC9#drycc
