apiVersion: v1
kind: Service
metadata:
  name: drycc-controller-api
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    app: drycc-controller
    heritage: drycc
    component: drycc-controller-api
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8000
  selector:
    app: drycc-controller
    component: drycc-controller-api
