# Generated by Django 4.2.10 on 2024-02-23 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='parameters',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='volume',
            name='type',
            field=models.CharField(choices=[('csi', 'container storage interface'), ('nfs', 'network file system')], default='csi'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='path',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='volume',
            name='size',
            field=models.CharField(default='0G', max_length=128),
        ),
    ]
