# Generated by Django 3.2.5 on 2021-12-08 02:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocklist',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(db_index=True, max_length=128)),
                ('type', models.PositiveIntegerField(choices=[(1, 'app'), (2, 'user')])),
                ('remark', models.TextField(blank=True, default='Blocked for unknown reason', null=True)),
            ],
            options={
                'ordering': ['-created'],
                'unique_together': {('id', 'type')},
            },
        ),
    ]
