# Generated by Django 4.2.10 on 2024-03-18 06:42

import api.models.limit
from django.db import migrations, models
import django.db.models.deletion
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_volume_parameters_volume_type_alter_volume_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitSpec',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=63, primary_key=True, serialize=False)),
                ('cpu', models.JSONField(validators=[functools.partial(api.models.limit.validate_json, *(), **{'schema': {'$schema': 'http://json-schema.org/schema#', 'properties': {'boost': {'type': 'string'}, 'clock': {'type': 'string'}, 'cores': {'type': 'integer'}, 'name': {'type': 'string'}, 'threads': {'type': 'integer'}}, 'required': ['name', 'cores', 'clock', 'boost', 'threads'], 'type': 'object'}})])),
                ('memory', models.JSONField(validators=[functools.partial(api.models.limit.validate_json, *(), **{'schema': {'$schema': 'http://json-schema.org/schema#', 'properties': {'size': {'type': 'string'}, 'type': {'type': 'string'}}, 'required': ['size', 'type'], 'type': 'object'}})])),
                ('features', models.JSONField(validators=[functools.partial(api.models.limit.validate_json, *(), **{'schema': {'$schema': 'http://json-schema.org/schema#', 'properties': {'gpu': {'$schema': 'http://json-schema.org/schema#', 'properties': {'cores': {'type': 'integer'}, 'memory': {'$schema': 'http://json-schema.org/schema#', 'properties': {'size': {'type': 'string'}, 'type': {'type': 'string'}}, 'required': ['size', 'type'], 'type': 'object'}, 'name': {'type': 'string'}, 'rops': {'type': 'integer'}, 'tmus': {'type': 'integer'}}, 'required': ['name', 'tmus', 'rops', 'cores'], 'type': 'object'}, 'network': {'type': 'string'}}, 'required': ['gpu', 'network'], 'type': 'object'}})])),
                ('keywords', models.JSONField(validators=[functools.partial(api.models.limit.validate_json, *(), **{'schema': {'$schema': 'http://json-schema.org/schema#', 'items': {'type': 'string'}, 'minItems': 1, 'type': 'array'}})])),
                ('disabled', models.BooleanField(default=False)),
                ('priority', models.SmallIntegerField(default=100)),
            ],
            options={
                'ordering': ['-priority'],
                'get_latest_by': 'created',
            },
        ),
        migrations.RemoveField(
            model_name='app',
            name='procfile_structure',
        ),
        migrations.RemoveField(
            model_name='config',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='config',
            name='memory',
        ),
        migrations.AddField(
            model_name='config',
            name='limits',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='LimitPlan',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=63, primary_key=True, serialize=False)),
                ('cpu', models.SmallIntegerField(default=1)),
                ('memory', models.SmallIntegerField(default=1)),
                ('features', models.JSONField(validators=[functools.partial(api.models.limit.validate_json, *(), **{'schema': {'$schema': 'http://json-schema.org/schema#', 'properties': {'gpu': {'type': 'integer'}, 'network': {'type': 'integer'}}, 'required': ['gpu', 'memory'], 'type': 'object'}})])),
                ('disabled', models.BooleanField(default=False)),
                ('priority', models.SmallIntegerField(default=100)),
                ('limits', models.JSONField(validators=[functools.partial(api.models.limit.validate_json, *(), **{'schema': {'$schema': 'http://json-schema.org/schema#', 'properties': {'cpu': {'type': 'integer'}, 'memory': {'type': 'integer'}}, 'required': ['cpu', 'memory'], 'type': 'object'}})])),
                ('requests', models.JSONField(default=dict)),
                ('annotations', models.JSONField(default=dict)),
                ('node_selector', models.JSONField(default=dict)),
                ('pod_security_context', models.JSONField(default=dict)),
                ('container_security_context', models.JSONField(default=dict)),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.limitspec')),
            ],
            options={
                'ordering': ['priority'],
                'get_latest_by': 'created',
            },
        ),
    ]
