# Generated by Django 4.2.10 on 2024-04-03 02:03

import api.models.service
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_limitspec_remove_app_procfile_structure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='dryccfile',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='release',
            name='state',
            field=models.TextField(choices=[('created', 'Release created but not deployed'), ('crashed', 'Release pipeline runtime crashed'), ('succeed', 'Release pipeline runtime succeed')], default='created'),
        ),
        migrations.AlterField(
            model_name='service',
            name='ports',
            field=models.JSONField(default=list, validators=[functools.partial(api.models.service.validate_json, *(), **{'schema': {'$schema': 'http://json-schema.org/schema#', 'items': {'properties': {'name': {'type': 'string'}, 'port': {'type': 'integer'}, 'protocol': {'type': 'string'}, 'targetPort': {'type': 'integer'}}, 'required': ['name', 'port', 'protocol', 'targetPort'], 'type': 'object'}, 'minItems': 1, 'type': 'array'}})]),
        ),
    ]
