# Generated by Django 4.2.10 on 2024-04-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_build_dryccfile_release_state_alter_service_ports'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='typed_values',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
