# Generated by Django 4.2.10 on 2024-05-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='procfile_type',
            field=models.TextField(default='web'),
        ),
    ]
