# Generated by Django 4.2.10 on 2024-05-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_domain_procfile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='procfile_type',
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name='route',
            name='procfile_type',
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name='service',
            name='procfile_type',
            field=models.CharField(max_length=63),
        ),
    ]
