# Generated by Django 4.2.11 on 2024-07-01 07:58

from django.db import migrations


def migration_route_rules(apps, schema_editor):
    route_model = apps.get_model('api', 'Route')
    for route in route_model.objects.all():
        if isinstance(route.rules, dict):
            route.rules = route.rules.get("stable")
        route.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_domain_procfile_type_alter_route_procfile_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsettings',
            name='canaries',
        ),
        migrations.RemoveField(
            model_name='release',
            name='canary',
        ),
        migrations.RemoveField(
            model_name='service',
            name='canary',
        ),
        migrations.RunPython(migration_route_rules),
    ]
