# Generated by Django 4.2.15 on 2024-08-14 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_appsettings_canaries_remove_release_canary_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['name', 'common_name', 'expires'], 'permissions': (('use_cert', 'Can use cert'),)},
        ),
    ]
