# Generated by Django 4.2.15 on 2024-08-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_appsettings_canaries_remove_release_canary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='autorollback',
            field=models.BooleanField(default=True),
        ),
    ]
