# Generated by Django 4.2.15 on 2024-08-15 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_certificate_options'),
        ('api', '0010_appsettings_autorollback'),
    ]

    operations = [
    ]
