# Generated by Django 4.2.15 on 2024-08-27 02:18

from django.db import migrations, models


def migration_dryccfile(apps, schema_editor):
    build_model = apps.get_model('api', 'Build')
    for build in build_model.objects.all():
        if build.dryccfile and isinstance(build.dryccfile.get('run'), dict):
            build.dryccfile['run'] = [build.dryccfile['run']]
            build.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_appsettings_autorollback'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='autodeploy',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(migration_dryccfile),
    ]
