# Generated by Django 4.2.15 on 2024-09-03 03:48

import api.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_appsettings_autodeploy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='app',
            options={'ordering': ['id'], 'verbose_name': 'Application'},
        ),
        migrations.RenameField(
            model_name='domain',
            old_name='procfile_type',
            new_name='ptype',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='procfile_type',
            new_name='ptype',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='procfile_type',
            new_name='ptype',
        ),
        migrations.AddField(
            model_name='certificate',
            name='app',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.app'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='release',
            name='conditions',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='name',
            field=models.CharField(max_length=253, validators=[api.utils.validate_label]),
        ),
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together={('app', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('app', 'ptype')},
        ),
    ]
