# Generated by Django 4.2.15 on 2024-09-03 03:48

from django.db import migrations
from api.models.domain import Domain
from api.models.certificate import Certificate


def migration_certificate(apps, schema_editor):
    for domain in Domain.objects.all():
        if domain.certificate:
            certificate = Certificate.objects.filter(
                app=domain.app, name=domain.certificate.name).first()
            if not certificate:
                certificate = domain.certificate
                certificate.pk = None
                certificate.app = domain.app
                certificate.save()
            domain.certificate = certificate
            domain.save()
    Certificate.objects.filter(app=None).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_app_options_rename_procfile_type_domain_ptype_and_more'),
    ]

    operations = [
        migrations.RunPython(migration_certificate),
    ]
