# Generated by Django 4.2.15 on 2024-09-06 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_migration_permissions_and_certificates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.app'),
        ),
    ]
