# Generated by Django 4.2.15 on 2024-09-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_certificate_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='autodeploy',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='autorollback',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='routable',
            field=models.BooleanField(default=None),
        ),
    ]
