# Generated by Django 4.2.15 on 2024-09-06 03:58

from django.db import migrations
from api.models.release import Release


def migration_deployed_ptypes(apps, schema_editor):
    for release in Release.objects.all().using("default"):
        deployed_ptypes = set()
        for condition in release.conditions:
            if condition["ptypes"] is None:
                deployed_ptypes = release.ptypes
                break
            else:
                deployed_ptypes = deployed_ptypes.union(condition["ptypes"])
        release.deployed_ptypes = list(deployed_ptypes)
        release.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_route_port_remove_route_ptype_and_more'),
    ]

    operations = [
        migrations.RunPython(migration_deployed_ptypes),
    ]
