# Generated by Django 4.2.18 on 2025-03-26 02:44

from django.db import migrations, models
from api.models.volume import Volume


def save_volume_to_k8s(apps, schema_editor):
    for volume in Volume.objects.all():
        if volume.type == 'nfs':
            volume.save_to_k8s()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_migration_deployed_ptypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='type',
            field=models.CharField(choices=[('csi', 'container storage interface'), ('nfs', 'network file system'), ('oss', 'object storage service file')], default='csi'),
        ),
        migrations.RunPython(save_volume_to_k8s),
    ]
