# Generated by Django 4.2.18 on 2025-03-26 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_migration_deployed_ptypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='type',
            field=models.CharField(choices=[('csi', 'container storage interface'), ('nfs', 'network file system'), ('oss', 'object storage service file')], default='csi'),
        ),
    ]
