# Generated by Django 4.2.22 on 2025-07-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_migration_k8s_alter_volume_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitplan',
            name='container_volume_mounts',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='limitplan',
            name='pod_volumes',
            field=models.JSONField(default=list),
        ),
    ]
