# Generated by Django 4.2.22 on 2025-08-22 02:48

import api.models.app
import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_limitplan_container_volume_mounts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='id',
            field=models.SlugField(max_length=63, null=True, unique=True, validators=[api.models.app.validate_app_id]),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='name',
            field=models.CharField(db_index=True, max_length=63, validators=[api.utils.validate_label]),
        ),
    ]
