# Generated by Django 4.2.22 on 2025-08-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_app_id_alter_gateway_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='suspended_state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
