# Generated by Django 5.2.8 on 2025-12-05 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_app_suspended_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='lifecycle_post_start',
            new_name='lifecycle',
        ),
        migrations.RemoveField(
            model_name='config',
            name='lifecycle_pre_stop',
        ),
    ]
