# Generated by Django 5.2.9 on 2026-03-23 05:42

import api.models.workspace
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_rename_lifecycle_post_start_config_lifecycle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=150, unique=True, validators=[api.models.workspace.validate_workspace_name], verbose_name='workspace name')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='app',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='appsettings',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='build',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='config',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='gateway',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='release',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='route',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='service',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='tls',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='volume',
            name='owner',
        ),
        migrations.AlterField(
            model_name='blocklist',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'app'), (2, 'workspace')]),
        ),
        migrations.AddField(
            model_name='app',
            name='workspace',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.workspace'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='WorkspaceInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('token', models.CharField(max_length=128, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False, verbose_name='accepted')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.workspace')),
            ],
            options={
                'unique_together': {('email', 'workspace')},
            },
        ),
        migrations.CreateModel(
            name='WorkspaceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], max_length=50)),
                ('alerts', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.workspace')),
            ],
            options={
                'unique_together': {('user', 'workspace')},
            },
        ),
    ]
