# Generated by Django 5.2.9 on 2026-03-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_workspace_remove_app_owner_remove_appsettings_owner_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='key',
            index=models.Index(fields=['fingerprint'], name='api_key_fingerp_4e77c5_idx'),
        ),
        migrations.AddIndex(
            model_name='limitplan',
            index=models.Index(fields=['spec', 'cpu', 'memory'], name='api_limitpl_spec_id_f95ef2_idx'),
        ),
        migrations.AddIndex(
            model_name='release',
            index=models.Index(fields=['app', 'failed', 'state'], name='api_release_app_id_9849f2_idx'),
        ),
    ]
