# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-02 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_config_termination_grace_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='tls',
            name='certs_auto_enabled',
            field=models.NullBooleanField(default=None),
        ),
    ]
