# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-02 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_tls_certs_auto_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='stack',
            field=models.CharField(max_length=32),
        ),
    ]
