# Generated by Django 5.2.9 on 2026-05-20 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_key_api_key_fingerp_4e77c5_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blocklist',
        ),
        migrations.RemoveField(
            model_name='app',
            name='suspended_state',
        ),
    ]
