name: controller
home: https://github.com/drycc/controller
apiVersion: v2
dependencies:
  - name: common
    repository: https://charts.drycc.cc/stable
    version: 1.x.x
description: Drycc Workflow Controller (API).
maintainers:
  - name: Drycc Team
    email: engineering@drycc.com
version: v1.0.0
