name: controller
home: https://github.com/drycc/controller
version: <Will be populated by the ci before publishing the chart>
description: Drycc Workflow Controller (API).
maintainers:
  - name: Drycc Team
    email: engineering@drycc.com
