imageOrg: "drycc"
imagePullPolicy: "Always"
imageTag: "canary"
imageRegistry: "registry.drycc.cc"
## Enable diagnostic mode
##
diagnosticMode:
  ## @param diagnosticMode.enabled Enable diagnostic mode (all probes will be disabled and the command will be overridden)
  ##
  enabled: false
  ## @param diagnosticMode.command Command to override all containers
  ##
  command:
    - sleep
  ## @param diagnosticMode.args Args to override all containers
  ##
  args:
    - infinity
# A comma-separated list of URLs to send app release information to
# See https://www.drycc.cc/managing-workflow/deploy-hooks/
deployHookUrls: ""
timezone: "UTC"
# Possible values are:
# enabled - allows for open registration
# disabled - turns off open registration
# admin_only - allows for registration by an admin only.
registrationMode: "admin_only"
# Option to disable ssl verification to connect to k8s api server
k8sApiVerifyTls: "true"
# Set app image pull policy
appImagePullPolicy: "Always"
# Filer settings image and image pull policy
filerImage: "registry.drycc.cc/drycc/filer:canary"
filerImagePullPolicy: "Always"
# Set app gateway, It is used for application gateway.
appGatewayClass: ""
# Set storageClassName, It is used for application mount.
appStorageClass: "longhorn"
# Set runtimeClassName. It is used for application.
appRuntimeClass: ""
# Set appDNSPolicy. It is used for application.
# See: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy
appDNSPolicy: ""
# set timeout seconds. It is used for pod exec
appPodExecTimeout: 3600
# Set api replicas
apiReplicas: 1
# Set celery replicas
celeryReplicas: 1
# Set mutate replicas
mutateReplicas: 1
# Set cronjob concurrencyPolicy
# Allow (default): The cron job allows concurrently running jobs
# Forbid: The cron job does not allow concurrent runs; if it is time for a new job run and the previous job run hasn't finished yet, the cron job skips the new job run
# Replace: If it is time for a new job run and the previous job run hasn't finished yet, the cron job replaces the currently running job run with a new job run
concurrencyPolicy: "Replace"
## valkeyUrl is will no longer use the built-in valkey component
valkeyUrl: ""
# databaseUrl and databaseReplicaUrl are will no longer use the built-in database component
databaseUrl: ""
databaseReplicaUrl: ""
# The passportUrl, passportKey and passportSecret are will no longer use the built-in passport component
passportUrl: ""
passportKey: ""
passportSecret: ""
# victoriametricsUrl is will no longer use the built-in victoriametrics component
victoriametricsUrl: ""
# Workflow-manager Configuration Options
workflowManagerUrl: ""
workflowManagerAccessKey: ""
workflowManagerSecretKey: ""
# Prefix for the imagepull secret created when using private registry
registrySecretPrefix: "private-registry"
# limit specs, plans config
config:
  metrics: ""
  limitSpecs: ""
  limitPlans: ""
  reservedNames: ""
  secretTemplate: ""
  volumeTemplate: ""
  volumeClaimTemplate: ""

# Service
service:
  # Provide any additional service annotations
  annotations: {}

# Any custom controller environment variables
# can be specified as key-value pairs under environment
# this is usually a non required setting.
environment: {}

api:
  resources: {}
    # limits:
    #   cpu: 200m
    #   memory: 50Mi
    # requests:
    #   cpu: 100m
    #   memory: 30Mi
  nodeAffinityPreset:
    key: "drycc.cc/node"
    type: "soft"
    values:
    - "true"
  podAffinityPreset:
    type: ""
    extraMatchLabels:
      security: "drycc-security"
  podAntiAffinityPreset:
    type: "soft"
    extraMatchLabels:
      app: "drycc-controller-api"

celery:
  resources: {}
    # limits:
    #   cpu: 200m
    #   memory: 50Mi
    # requests:
    #   cpu: 100m
    #   memory: 30Mi
  nodeAffinityPreset:
    key: "drycc.cc/node"
    type: "soft"
    values:
    - "true"
  podAffinityPreset:
    type: ""
    extraMatchLabels:
      security: "drycc-security"
  podAntiAffinityPreset:
    type: "soft"
    extraMatchLabels:
      app: "drycc-controller-celery"

mutate:
  resources: {}
    # limits:
    #   cpu: 200m
    #   memory: 50Mi
    # requests:
    #   cpu: 100m
    #   memory: 30Mi
  nodeAffinityPreset:
    key: "drycc.cc/node"
    type: "soft"
    values:
    - "true"
  podAffinityPreset:
    type: ""
    extraMatchLabels:
      security: "drycc-security"
  podAntiAffinityPreset:
    type: "soft"
    extraMatchLabels:
      component: "drycc-controller-mutate"

valkey:
  enabled: true

database:
  enabled: true

quickwit:
  logIndexPrefix: logs-

registry:
  enabled: true

passport:
  enabled: true

victoriametrics:
  enabled: true

global:
  # Admin email, used for each component to send email to administrator
  email: "drycc@drycc.cc"
  # The public resolvable hostname to build your cluster with.
  #
  # This will be the hostname that is used to build endpoints such as "drycc.$HOSTNAME"
  platformDomain: ""
  # Whether cert_manager is enabled to automatically generate controller certificates
  certManagerEnabled: true
