imageOrg: "drycc"
imagePullPolicy: "Always"
imageTag: "canary"
imageRegistry: "registry.drycc.cc"
appImagePullPolicy: "Always"
# A comma-separated list of URLs to send app release information to
# See https://www.drycc.cc/managing-workflow/deploy-hooks/
deployHookUrls: ""
# limitsCpu: "100m"
# limitsMemory: "50Mi"
# Possible values are:
# enabled - allows for open registration
# disabled - turns off open registration
# admin_only - allows for registration by an admin only.
registrationMode: "admin_only"
# Option to disable ssl verification to connect to k8s api server
k8sApiVerifyTls: "true"

# Set storageClassName, It is used for application mount.
appStorageClass: ""
# Set controller deployment  replicas
replicas: 1
# Set celery replicas
celeryReplicas: 1
# Set cronjob concurrencyPolicy
# Allow (default): The cron job allows concurrently running jobs
# Forbid: The cron job does not allow concurrent runs; if it is time for a new job run and the previous job run hasn't finished yet, the cron job skips the new job run
# Replace: If it is time for a new job run and the previous job run hasn't finished yet, the cron job replaces the currently running job run with a new job run
concurrencyPolicy: "Replace"
# Configuring this will no longer use the built-in database component
databaseUrl: ""
# Configuring this will no longer use the built-in rabbitmq component
rabbitmqUrl: ""
# Service
service:
  # Provide any additional service annotations
  annotations: {}
# Any custom controller environment variables
# can be specified as key-value pairs under environment
# this is usually a non required setting.
environment:
  RESERVED_NAMES: "drycc, drycc-builder, drycc-monitor-grafana"

api:
  nodeAffinityPreset:
    key: "drycc.cc/node"
    type: "soft"
    values:
    - "true"
  podAffinityPreset:
    key: "security"
    type: ""
    values:
    - "drycc-security"
  podAntiAffinityPreset:
    key: "app"
    type: "soft"
    values:
    - "drycc-controller-api"

celery:
  nodeAffinityPreset:
    key: "drycc.cc/node"
    type: "soft"
    values:
    - "true"
  podAffinityPreset:
    key: "security"
    type: ""
    values:
    - "drycc-security"
  podAntiAffinityPreset:
    key: "app"
    type: "soft"
    values:
    - "drycc-controller-celery"

webhook:
  nodeAffinityPreset:
    key: "drycc.cc/node"
    type: "soft"
    values:
    - "true"
  podAffinityPreset:
    key: "security"
    type: ""
    values:
    - "drycc-security"
  podAntiAffinityPreset:
    key: "app"
    type: "soft"
    values:
    - "drycc-controller-webhook"

cronjob:
  nodeAffinityPreset:
    key: "drycc.cc/node"
    type: "soft"
    values:
    - "true"
  podAffinityPreset:
    key: "security"
    type: ""
    values:
    - "drycc-security"
  podAntiAffinityPreset:
    key: "app"
    type: "soft"
    values:
    - "drycc-controller-webhook"

redis:
  replicas: 1

global:
  # Admin email, used for each component to send email to administrator
  email: "drycc@drycc.cc"
  # Set the storage backend
  #
  # Valid values are:
  # - s3: Store persistent data in AWS S3 (configure in S3 section)
  # - azure: Store persistent data in Azure's object storage
  # - gcs: Store persistent data in Google Cloud Storage
  # - minio: Store persistent data on in-cluster Minio server
  storage: minio
  # Set the location of Workflow's PostgreSQL database
  #
  # Valid values are:
  # - on-cluster: Run PostgreSQL within the Kubernetes cluster (credentials are generated
  #   automatically; backups are sent to object storage
  #   configured above)
  # - off-cluster: Run PostgreSQL outside the Kubernetes cluster (configure in database section)
  databaseLocation: "on-cluster"

  # Set the location of Workflow's Registry
  #
  # Valid values are:
  # - on-cluster: Run registry within the Kubernetes cluster
  # - off-cluster: Use registry outside the Kubernetes cluster (example: dockerhub,self-hosted)
  registryLocation: "on-cluster"
  # The host port to which registry proxy binds to
  registryProxyPort: 5555
  # Prefix for the imagepull secret created when using private registry
  registrySecretPrefix: "private-registry"
  # Role-Based Access Control for Kubernetes >= 1.5
  rbac: false
  # Please check `kubernetes.io/ingress.class`
  ingressClass: ""
  # A domain name consists of one or more parts.
  # Periods (.) are used to separate these parts.
  # Each part must be 1 to 63 characters in length and can contain lowercase letters, digits, and hyphens (-).
  # It must start and end with a lowercase letter or digit.
  clusterDomain: "cluster.local"
  # The public resolvable hostname to build your cluster with.
  #
  # This will be the hostname that is used to build endpoints such as "drycc.$HOSTNAME"
  platformDomain: ""
  # Whether cert_manager is enabled to automatically generate controller certificates
  certManagerEnabled: true
  passportLocation: "on-cluster"
