{{- if .Values.global.cert_manager_enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: drycc-controller
spec:
  secretName: drycc-controller-certificate-auto
  issuerRef:
    name: drycc-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
  - drycc.{{ .Values.global.platform_domain }}
  privateKey:
    rotationPolicy: Always
{{- end }}
