apiVersion: v1
kind: ConfigMap
metadata:
  name: controller-config
  labels:
    heritage: drycc
data:
  metrics.json: |
    {{- if .Values.config.metrics }}
    {{- (tpl .Values.config.metrics $) | nindent 4 }}
    {{- else}}
    {{- include "controller.config.defaultMetrics" . | fromYaml | toPrettyJson | nindent 4 }}
    {{- end }}
  limit-specs.json: |
    {{- if .Values.config.limitSpecs }}
    {{- (tpl .Values.config.limitSpecs $)  | nindent 4 }}
    {{- else}}
    {{- include "controller.config.defaultLimitSpecs" . | fromYamlArray | toPrettyJson | nindent 4 }}
    {{- end }}
  limit-plans.json: |
    {{- if .Values.config.limitPlans }}
    {{- (tpl .Values.config.limitPlans $)  | nindent 4 }}
    {{- else}}
    {{- include "controller.config.defaultLimitPlans" . | fromYamlArray | toPrettyJson | nindent 4 }}
    {{- end }}
  reserved-names.txt: |-
    {{- if .Values.config.reservedNames }}
    {{- (tpl .Values.config.reservedNames $)  | nindent 4 }}
    {{- else}}
    {{- include "controller.config.defaultReservedNames" . | nindent 4 }}
    {{- end }}
  secret-template.json: |
    {{- if .Values.config.secretTemplate }}
    {{- (tpl .Values.config.secretTemplate $)  | nindent 4 }}
    {{- else}}
    {{- include "controller.config.defaultSecretTemplate" . | fromYaml | toPrettyJson | nindent 4 }}
    {{- end }}
  volume-template.json: |
    {{- if .Values.config.volumeTemplate }}
    {{- (tpl .Values.config.volumeTemplate $)  | nindent 4 }}
    {{- else}}
    {{- include "controller.config.defaultVolumeTemplate" . | fromYaml | toPrettyJson | nindent 4 }}
    {{- end }}
  volume-claim-template.json: |
    {{- if .Values.config.volumeClaimTemplate }}
    {{- (tpl .Values.config.volumeClaimTemplate $)  | nindent 4 }}
    {{- else}}
    {{- include "controller.config.defaultVolumeClaimTemplate" . | fromYaml | toPrettyJson | nindent 4 }}
    {{- end }}
