apiVersion: apps/v1
kind: Deployment
metadata:
  name: drycc-controller
  labels:
    heritage: drycc
  annotations:
    component.drycc.cc/version: {{ .Values.image_tag }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: drycc-controller
  template:
    metadata:
      labels:
        app: drycc-controller
    spec:
      serviceAccount: drycc-controller
      containers:
        - name: drycc-controller
          image: {{.Values.image_registry}}/{{.Values.org}}/controller:{{.Values.image_tag}}
          imagePullPolicy: {{.Values.image_pull_policy}}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8000
            initialDelaySeconds: 30
            timeoutSeconds: 10
            periodSeconds: 5
          ports:
            - containerPort: 8000
              name: http
          {{- include "controller.limits" . | indent 10 }}
          {{- include "controller.envs" . | indent 10 }}
