{{- if (.Values.global.use_rbac) -}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: drycc:drycc-controller
  labels:
    app: drycc-controller
    heritage: drycc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: drycc:drycc-controller
subjects:
- kind: ServiceAccount
  name: drycc-controller
  namespace: {{ .Release.Namespace }}
{{- end -}}
