{{- if .Values.global.certManagerEnabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: drycc-controller
spec:
  secretName: drycc-controller-auto-tls
  issuerRef:
    name: drycc-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
  - drycc.{{ .Values.global.platformDomain }}
  privateKey:
    rotationPolicy: Always
{{- end }}
