{{ if .Values.cert_manager_enabled }}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: drycc-controller
  namespace: "{{ .Release.Namespace }}"
spec:
  secretName: drycc-controller-auto-tls
  issuerRef:
    name: drycc-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
  - drycc.{{ .Values.platform_domain }}
  # acme:
  #   config:
  #   - http01:
  #       ingressClass: "{{ .Values.global.ingress_class }}"
  #     domains:
  #     - drycc.{{ .Values.platform_domain }}
{{- end }}
