kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ printf "%s:drycc-controller" .Release.Namespace | quote }}
  labels:
    app: drycc-controller
    heritage: drycc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ printf "%s:drycc-controller" .Release.Namespace | quote }}
subjects:
- kind: ServiceAccount
  name: drycc-controller
  namespace: {{ .Release.Namespace }}
