apiVersion: v1
kind: Secret
metadata:
  name: controller-creds
  labels:
    heritage: drycc
data:
  {{- if (.Values.valkeyUrl) }}
  valkey-url: {{ .Values.valkeyUrl | b64enc }}
  {{- end }}
  {{- if (.Values.databaseUrl) }}
  database-url: {{ .Values.databaseUrl | b64enc }}
  {{- end }}
  {{- if (.Values.databaseReplicaUrl) }}
  database-replica-url: {{ .Values.databaseReplicaUrl | b64enc }}
  {{- end }}
  {{- if (.Values.prometheusUrl) }}
  prometheus-url: {{ .Values.prometheusUrl | b64enc }}
  {{- end }}
  {{- if (.Values.passportUrl) }}
  passport-url: {{ .Values.passportUrl | b64enc }}
  {{- end }}
  {{- if (.Values.passportKey) }}
  passport-key: {{ .Values.passportKey | b64enc }}
  {{- end }}
  {{- if (.Values.passportSecret) }}
  passport-secret: {{ .Values.passportSecret | b64enc }}
  {{- end }}
  django-secret-key: {{ (include "common.secrets.lookup" (dict "secret" "controller-creds" "key" "django-secret-key" "defaultValue" (randAscii 64) "context" $)) }}
  deploy-hook-secret-key: {{ (include "common.secrets.lookup" (dict "secret" "controller-creds" "key" "deploy-hook-secret-key" "defaultValue" (randAscii 64) "context" $)) }}
