apiVersion: apps/v1
kind: Deployment
metadata:
  name: drycc-controller-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      component: drycc-controller-webhook
  template:
    metadata:
      labels:
        component: drycc-controller-webhook
    spec:
      {{- include "common.affinities.pods.soft" (dict "key" "app" "values" (list "drycc-controller-webhook")) | indent 6 }}
      initContainers:
      - name: drycc-controller-init
        image: {{.Values.imageRegistry}}/{{.Values.imageOrg}}/python-dev:latest
        imagePullPolicy: {{.Values.imagePullPolicy}}
        args:
        - netcat
        - -v
        - -u
        - $(DRYCC_DATABASE_URL),$(DRYCC_RABBITMQ_URL)
        - -a
        - $(DRYCC_REDIS_ADDRS)
        {{- include "controller.envs" . | indent 8 }}
      containers:
      - name: drycc-controller
        image: {{.Values.imageRegistry}}/{{.Values.imageOrg}}/controller:{{.Values.imageTag}}
        imagePullPolicy: {{.Values.imagePullPolicy}}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 30
          timeoutSeconds: 10
          periodSeconds: 5
        ports:
          - containerPort: 8443
            name: https
        volumeMounts:
        - name: drycc-controller-webhook-cert
          mountPath: /etc/controller/webhook/cert
        {{- include "controller.limits" . | indent 8 }}
        {{- include "controller.envs" . | indent 8 }}
      volumes:
      - name: drycc-controller-webhook-cert                                                                                                                                                                                               
        secret:                                                                                                                                                                                                                           
          secretName: drycc-controller-webhook-cert                                                                                                                                                                                       
          items:  
          - key: token                                                                                                                                                                                                                  
            path: token                                                                                                                                                                                                                           
          - key: tls.crt                                                                                                                                                                                                                  
            path: tls.crt                                                                                                                                                                                                                 
          - key: tls.key                                                                                                                                                                                                                  
            path: tls.key