apiVersion: v1
kind: Secret
metadata:
  name: django-secret-key
  labels:
    heritage: drycc
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  secret-key: {{ randAscii 64 | b64enc }}
