apiVersion: v1
kind: Secret
metadata:
  name: controller-creds
  labels:
    heritage: drycc
  annotations:
    "helm.sh/hook": pre-install
data:
  {{- if (.Values.databaseUrl) }}
  database-url: {{ .Values.databaseUrl | b64enc }}
  {{- end }}
  {{- if (.Values.databaseReplicaUrl) }}
  database-replica-url: {{ .Values.databaseReplicaUrl | b64enc }}
  {{- end }}
  django-secret-key: {{ randAscii 64 | b64enc }}
  deploy-hook-secret-key: {{ randAscii 64 | b64enc }}