apiVersion: v1
kind: Service
metadata:
  name: drycc-controller
  labels:
    heritage: drycc
    router.drycc.cc/routable: "true"
  annotations:
    router.drycc.cc/domains: drycc
    router.drycc.cc/connectTimeout: "10"
    router.drycc.cc/tcpTimeout: "1200"
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8000
  selector:
    app: drycc-controller
