apiVersion: v1
kind: Secret
metadata:
  name: controller-creds
  labels:
    heritage: drycc
  annotations:
    "helm.sh/hook": pre-install
data:
  {{- if (.Values.database_url) }}
  database-url: {{ .Values.database_url | b64enc }}
  {{- end }}
  django-secret-key: {{ randAscii 64 | b64enc }}
  deploy-hook-secret-key: {{ randAscii 64 | b64enc }}