{{ if .Values.cert_manager_enabled }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: drycc-controller
  namespace: "{{ .Release.Namespace }}"
spec:
  secretName: drycc-controller-auto-tls
  issuerRef:
    name: drycc-letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - drycc.{{ .Values.platform_domain }}
  acme:
    config:
    - http01:
        ingressClass: "{{ .Values.global.ingress_class }}"
      domains:
      - drycc.{{ .Values.platform_domain }}
{{- end }}
