apiVersion: v1
kind: Service
metadata:
  name: drycc-controller
  labels:
    heritage: drycc
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8000
  selector:
    app: drycc-controller
