apiVersion: batch/v1
kind: CronJob
metadata:
  name: drycc-controller-cronjob-hourly
  labels:
    heritage: drycc
  annotations:
    component.drycc.cc/version: {{ .Values.imageTag }}
spec:
  schedule: "0 */1 * * *"
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccount: drycc-controller
          initContainers:
          - name: drycc-controller-init
            image: {{.Values.imageRegistry}}/{{.Values.imageOrg}}/python-dev:latest
            imagePullPolicy: {{.Values.imagePullPolicy}}
            args:
              - netcat
              - -v
              - -u
              - $(DRYCC_DATABASE_URL),$(DRYCC_RABBITMQ_URL)
              - -a
              - $(DRYCC_REDIS_ADDRS)
            {{- include "controller.envs" . | indent 12 }}
          containers:
          - image: {{.Values.imageRegistry}}/{{.Values.imageOrg}}/controller:{{.Values.imageTag}}
            imagePullPolicy: {{.Values.pull_policy}}
            name: drycc-controller-measure-networks
            args:
            - /bin/bash
            - -c
            - python -u /workspace/manage.py measure_networks
            {{- include "controller.envs" . | indent 12 }}
