apiVersion: apps/v1
kind: Deployment
metadata:
  name: drycc-controller-celery
  labels:
    heritage: drycc
  annotations:
    component.drycc.cc/version: {{ .Values.imageTag }}
spec:
  replicas: {{ .Values.celeryReplicas }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: drycc-controller-celery
  template:
    metadata:
      labels:
        app: drycc-controller-celery
    spec:
      serviceAccount: drycc-controller
      initContainers:
      - name: drycc-controller-init
        image: docker.io/drycc/python-dev:latest
        imagePullPolicy: {{.Values.imagePullPolicy}}
        args:
          - netcat
          - -v
          - -u
          - $(DRYCC_DATABASE_URL),$(DRYCC_RABBITMQ_URL)
          - -a
          - $(DRYCC_REDIS_ADDRS)
        {{- include "controller.envs" . | indent 8 }}
      containers:
      - name: drycc-controller-celery-high
        image: {{.Values.imageRegistry}}/{{.Values.imageOrg}}/controller:{{.Values.imageTag}}
        imagePullPolicy: {{.Values.imagePullPolicy}}
        args:
          - /bin/bash
          - -c
          - celery -A api worker -Q priority.high --autoscale=32,1 --loglevel=WARNING
        {{- include "controller.limits" . | indent 8 }}
        {{- include "controller.envs" . | indent 8 }}
      - name: drycc-controller-celery-middle
        image: {{.Values.imageRegistry}}/{{.Values.imageOrg}}/controller:{{.Values.imageTag}}
        imagePullPolicy: {{.Values.imagePullPolicy}}
        args:
          - /bin/bash
          - -c
          - celery -A api worker -Q priority.middle --autoscale=16,1 --loglevel=WARNING
        {{- include "controller.limits" . | indent 8 }}
        {{- include "controller.envs" . | indent 8 }}
      - name: drycc-controller-celery-low
        image: {{.Values.imageRegistry}}/{{.Values.imageOrg}}/controller:{{.Values.imageTag}}
        imagePullPolicy: {{.Values.imagePullPolicy}}
        args:
          - /bin/bash
          - -c
          - celery -A api worker -Q priority.low --autoscale=8,1 --loglevel=WARNING
        {{- include "controller.limits" . | indent 8 }}
        {{- include "controller.envs" . | indent 8 }}

