{{- if (.Values.global.rbac) -}}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ printf "%s:drycc-controller" .Release.Namespace | quote }}
  labels:
    app: drycc-controller
    heritage: drycc
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "create", "patch", "update", "delete"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
- apiGroups: ["events.k8s.io"]
  resources: ["events"]
  verbs: ["list", "create"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["list", "get", "create", "patch", "update", "delete"]
- apiGroups: [""]
  resources: ["replicationcontrollers"]
  verbs: ["get", "list", "create", "update", "delete"]
- apiGroups: [""]
  resources: ["replicationcontrollers/scale"]
  verbs: ["get", "update"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["get", "create"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["resourcequotas"]
  verbs: ["get", "create"]
- apiGroups: [""]
  resources: ["limitranges"]
  verbs: ["get", "create"]
- apiGroups: ["extensions"]
  resources: ["replicasets"]
  verbs: ["get", "list", "delete", "update"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments/scale", "replicasets/scale"]
  verbs: ["get", "update"]
- apiGroups: ["extensions", "autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "create", "update", "delete"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
- apiGroups: ["cert-manager.io"]
  resources: ["certificates", "certificaterequest", "issuers"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "create", "delete", "deletecollection", "patch", "update"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingressclasses"]
  verbs: ["get"]
- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["get", "list", "watch", "delete"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
- apiGroups: ["servicecatalog.k8s.io"]
  resources: ["clusterserviceclasses", "serviceclasses", "clusterserviceplans", "serviceplans"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["servicecatalog.k8s.io"]
  resources: ["serviceinstances", "servicebindings"]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
- apiGroups: ["gateway.networking.k8s.io"]
  resources: ["gateways", "httproutes", "grocroutes", "tcproutes", "udproutes", "tlsroutes"]
  verbs: ["get", "patch", "list", "create", "update", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create"]
{{- end -}}

