{{- if (.Values.global.use_rbac) -}}
{{- if (.Capabilities.APIVersions.Has (include "rbacAPIVersion" .)) -}}
kind: ClusterRoleBinding
apiVersion: {{ template "rbacAPIVersion" . }}
metadata:
  name: drycc:drycc-controller
  labels:
    app: drycc-controller
    heritage: drycc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: drycc:drycc-controller
subjects:
- kind: ServiceAccount
  name: drycc-controller
  namespace: {{ .Release.Namespace }}
{{- end -}}
{{- end -}}
