{{ if not (eq .Values.global.ingress_class "") }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: "controller-api-server-ingress"
  labels:
    app: "controller"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "{{ .Values.global.ingress_class }}"
spec:
  rules:
  - host: drycc.{{ .Values.platform_domain }}
    http:
      paths:
      {{- if eq .Values.global.ingress_class "gce" "alb" }}
      - path: /*
      {{- else }}{{/* Has annotations but ingress class is not "gce" nor "alb" */}}
      - path: /
      {{- end }}
        backend:
          serviceName: drycc-controller
          servicePort: 80
{{- end }}
