apiVersion: batch/v1
kind: Job
metadata:
  name: drycc-controller-job-upgrade
  annotations:
    component.drycc.cc/version: {{ .Values.imageTag }}
    helm.sh/hook: post-install,pre-upgrade,pre-rollback
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  template:
    spec:
      serviceAccount: drycc-controller
      initContainers:
      - name: drycc-controller-job-upgrade-init
        image: {{.Values.imageRegistry}}/{{.Values.imageOrg}}/python-dev:latest
        imagePullPolicy: {{.Values.imagePullPolicy}}
        args:
        - netcat
        - -v
        - -u
        - $(DRYCC_DATABASE_URL),$(DRYCC_VALKEY_URL),$(DRYCC_DATABASE_REPLICA_URL)
        {{- include "controller.envs" . | indent 8 }}
      containers:
      - name: drycc-controller-job-upgrade
        image: {{.Values.imageRegistry}}/{{.Values.imageOrg}}/controller:{{.Values.imageTag}}
        imagePullPolicy: {{.Values.imagePullPolicy}}
        {{- if .Values.diagnosticMode.enabled }}
        command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 8 }}
        args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 8 }}
        {{- else }}
        args:
        - /usr/bin/env
        - bash
        - -ec
        - |
          python -u /workspace/manage.py migrate --noinput
          python -u /workspace/manage.py loaddata /etc/controller/limit-specs.json
          python -u /workspace/manage.py loaddata /etc/controller/limit-plans.json
        {{- end }}
        {{- include "controller.envs" . | indent 8 }}
        volumeMounts:
        - name: controller-config
          readOnly: false
          mountPath: /etc/controller
      volumes:
      - name: controller-config
        configMap:
          name: controller-config
      restartPolicy: Never
