{{ if .Values.global.experimental_native_ingress }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: "controller-api-server-ingress-http"
  labels:
    app: "controller"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  rules:
  - host: drycc.{{ .Values.platform_domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: drycc-controller
          servicePort: 80
{{- end }}
