apiVersion: v1
kind: ConfigMap
metadata:
  name: controller-config
  labels:
    heritage: drycc
data:
  limit-specs.json: |
    {{- if .Values.config.limitSpecs }}
    {{- (tpl .Values.config.limitSpecs $)  | nindent 4 }}
    {{- else}}
    {{- include "controller.config.defaultLimitSpecs" . | fromYamlArray | toPrettyJson | nindent 4 }}
    {{- end }}
  limit-plans.json: |
    {{- if .Values.config.limitPlans }}
    {{- (tpl .Values.config.limitPlans $)  | nindent 4 }}
    {{- else}}
    {{- include "controller.config.defaultLimitPlans" . | fromYamlArray | toPrettyJson | nindent 4 }}
    {{- end }}
